apiVersion: v1
kind: Service
metadata:
  name: ums-client
spec:
  selector:
    app: ums-client
  ports:
    - port: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-client
  labels:
    app: ums-client
spec:
  replicas: 1
  template:
    metadata:
      name: ums-client
      labels:
        app: ums-client
    spec:
      containers:
        - name: ums-client
          image: cloudhubs2/tms-ums-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: ums-client
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ums-client
spec:
  rules:
    - host: tcs.ecs.baylor.edu
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: cms-client
                port:
                  number: 80
          - path: /exams
            pathType: Prefix
            backend:
              service:
                name: ems-client
                port:
                  number: 80
          - path: /questions
            pathType: Prefix
            backend:
              service:
                name: qms-client
                port:
                  number: 80
          - path: /cms
            pathType: Prefix
            backend:
              service:
                name: cms
                port:
                  number: 80
          - path: /ems
            pathType: Prefix
            backend:
              service:
                name: ems
                port:
                  number: 80
          - path: /qms
            pathType: Prefix
            backend:
              service:
                name: qms
                port:
                  number: 80
          - path: /ums
            pathType: Prefix
            backend:
              service:
                name: ums
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ums-client
                port:
                  number: 80